config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  get '/users/finish_signup', to: 'users#finish_signup', as: 'finish_signup'
  patch '/users/finish_signup/update', to: 'users#update_profile', as: 'update_profile'

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: :commentable, shallow: true do
    resources :answers, concerns: :commentable
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create], shallow: true do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

  root 'questions#index'

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#  author_id  :integer          not null
#

class Question < ActiveRecord::Base

  default_scope { order(created_at: :desc) }

  belongs_to :author, class_name: 'User'
  has_many :answers, -> { order 'created_at DESC' }, dependent: :destroy
  has_many :attachments, as: :attachmentable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  validates :body, presence: true
  validates :title, presence: true, length: { maximum: 255 }

  paginates_per 15
  is_impressionable counter_cache: true, unique: :request_hash

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions, each_serializer: QuestionsSerializer
  end

  def show
    respond_with @question = Question.find(params[:id])
  end

  def create
    respond_with(@questoion = Question.create(question_params
      .merge(author: current_resource_owner)))
  end

  private
  
  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController <  ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :set_answer, only: [:show]
  after_action :publish_question, only: [:create, :update, :destroy]

  impressionist actions: [:show]
  authorize_resource
  respond_to :html

  def index
    respond_with @questions = Question.page(params[:page])
  end

  def show
    respond_with @question
  end

  def new
    respond_with @question = Question.new
  end

  def create
    respond_with @question = current_user.questions.create(question_params)
  end

  def edit
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with @question.destroy
  end

  private

  def publish_question
    case action_name
    when 'destroy'
      PrivatePub.publish_to('/questions',
                            question_id: @question.id,
                            action: action_name)
    else
      PrivatePub.publish_to('/questions',
                            question: QuestionsSerializer.new(@question, root: false).to_json,
                            action: action_name) if @question.valid?
    end
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def set_answer
    @answer = Answer.new
  end
end

app/views/questions/_form.html.slim
- if @question.errors.any?
  ul.alert-box.alert
    - @question.errors.full_messages.each do |message|
      li = message

= nested_form_for @question do |f|
  p
    = f.label :title
    = f.text_field :title, class: "form-control"
  p
    = f.label :body
    = f.text_area :body, class: "form-control"
 
  p#attachments
    = f.fields_for :attachments do |attachment_fields|
      = render 'shared/attachment_fields', a: attachment_fields
    = f.link_to_add "Add file", :attachments, class: 'button tiny'

  = f.submit "Save question", class: "button"

app/views/questions/_question.html.slim
li.question data={question: question.id}
  .row.collapse 
    .large-3.columns
      .row.collapse
        .large-6.columns.text-center.answers-count
          strong #{question.answers.count}
          br
          span answers
        .large-6.columns.text-center.views-count
          strong #{question.impressionist_count}
          br
          span views
    .large-9.columns
        h3.question-link.row.collapse
          = link_to question.title, question
        .row.collapse
          .right
            .question-author
              | by  
              | #{question.author.username} 
              | #{time_ago_in_words(question.created_at)} ago

app/views/questions/edit.html.slim
= render 'form'

app/views/questions/index.html.slim
ul.questions
  = render @questions

= paginate @questions

= subscribe_to "/questions"

app/views/questions/new.html.slim
- provide(:title, 'Create new question')

= render 'form'

app/views/questions/show.html.slim
.question
  h2 = @question.title
  hr

  - if can? :update, @question
    ul.button-group.right
      li = link_to "Edit question", edit_question_path, class: 'button tiny'
      li = link_to "Delete question", @question, method: :delete, data: { confirm: true }, class: 'button alert tiny'

  p = @question.body

  - if @question.attachments.any?
    p Attachments: 
    ul
      - @question.attachments.each do |a|
        li = link_to a.file.identifier, a.file.url

  .comments
    = render @question.comments
    - if user_signed_in?
      = link_to 'Add a comment', '', class: 'button tiny add-comment'

br

h2.answers-title = pluralize(@question.answers.count, "Answer")
.answers data={ question_id: @question.id }
  = render @question.answers

- if user_signed_in?
  = render 'answers/form', question: @question, answer: @answer
- else
   p
    ' You should
    => link_to 'sign in', new_user_session_path
    ' or
    => link_to 'sign up', new_user_registration_path
    ' to answer this question.

= subscribe_to "/questions/#{@question.id}"